# Use the official Apache image from the Docker Hub
FROM httpd:2.4

# Copy the current directory contents into the container at /usr/local/apache2/htdocs/
COPY . /usr/local/apache2/htdocs/

# Expose port 80
EXPOSE 80

